package PBOpraktek.GUI2.Shape;

import javax.swing.JOptionPane;
//import shape.*;

/**
 *
 * @author Rochana
 */
public class ShapeApp extends javax.swing.JFrame {

    static boolean persegi;
    static boolean segiempat;
    static boolean segitiga;
    static boolean lingkaran;

    /**
     * Creates new form ShapeApp
     */
    public ShapeApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1_segiempat = new javax.swing.JPanel();
        jButton1_segiempat = new javax.swing.JButton();
        jPanel2_persegi = new javax.swing.JPanel();
        jButton2_persegi = new javax.swing.JButton();
        jPanel3_lingkaran = new javax.swing.JPanel();
        jButton3_lingkaran = new javax.swing.JButton();
        jPanel4_segitiga = new javax.swing.JPanel();
        jButton4_segitiga = new javax.swing.JButton();
        Bangun2D = new javax.swing.JLabel();
        LuasdanKeliling = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        inputPanjang = new javax.swing.JLabel();
        inputLebar = new javax.swing.JLabel();
        inputSisiJari = new javax.swing.JLabel();
        jTextField1_panjang = new javax.swing.JTextField();
        jTextField2_lebar = new javax.swing.JTextField();
        jTextField3_sisijari = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jButton5_exit = new javax.swing.JButton();
        jButton6_hitung = new javax.swing.JButton();
        jButton7_reset = new javax.swing.JButton();
        LuasArea = new javax.swing.JLabel();
        Keliling = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        hasilLuas = new javax.swing.JLabel();
        hasilKeliling = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(35, 80, 135));

        jPanel1_segiempat.setBackground(new java.awt.Color(211, 220, 231));

        jButton1_segiempat.setBackground(new java.awt.Color(255, 255, 204));
        jButton1_segiempat.setText("SEGIEMPAT");
        jButton1_segiempat.setBorderPainted(false);
        jButton1_segiempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_segiempatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_segiempatLayout = new javax.swing.GroupLayout(jPanel1_segiempat);
        jPanel1_segiempat.setLayout(jPanel1_segiempatLayout);
        jPanel1_segiempatLayout.setHorizontalGroup(
                jPanel1_segiempatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_segiempatLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jButton1_segiempat)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_segiempatLayout.setVerticalGroup(
                jPanel1_segiempatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_segiempatLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1_segiempat, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110))
        );

        jPanel2_persegi.setBackground(new java.awt.Color(255, 111, 97));

        jButton2_persegi.setBackground(new java.awt.Color(255, 255, 204));
        jButton2_persegi.setText("PERSEGI");
        jButton2_persegi.setBorderPainted(false);
        jButton2_persegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_persegiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2_persegiLayout = new javax.swing.GroupLayout(jPanel2_persegi);
        jPanel2_persegi.setLayout(jPanel2_persegiLayout);
        jPanel2_persegiLayout.setHorizontalGroup(
                jPanel2_persegiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2_persegiLayout.createSequentialGroup()
                                .addContainerGap(68, Short.MAX_VALUE)
                                .addComponent(jButton2_persegi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69))
        );
        jPanel2_persegiLayout.setVerticalGroup(
                jPanel2_persegiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2_persegiLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2_persegi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105))
        );

        jPanel3_lingkaran.setBackground(new java.awt.Color(255, 226, 223));

        jButton3_lingkaran.setBackground(new java.awt.Color(255, 255, 204));
        jButton3_lingkaran.setText("LINGKARAN");
        jButton3_lingkaran.setBorderPainted(false);
        jButton3_lingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_lingkaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3_lingkaranLayout = new javax.swing.GroupLayout(jPanel3_lingkaran);
        jPanel3_lingkaran.setLayout(jPanel3_lingkaranLayout);
        jPanel3_lingkaranLayout.setHorizontalGroup(
                jPanel3_lingkaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3_lingkaranLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jButton3_lingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel3_lingkaranLayout.setVerticalGroup(
                jPanel3_lingkaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3_lingkaranLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3_lingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106))
        );

        jPanel4_segitiga.setBackground(new java.awt.Color(239, 192, 80));

        jButton4_segitiga.setBackground(new java.awt.Color(255, 255, 204));
        jButton4_segitiga.setText("SEGITIGA");
        jButton4_segitiga.setBorderPainted(false);
        jButton4_segitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_segitigaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4_segitigaLayout = new javax.swing.GroupLayout(jPanel4_segitiga);
        jPanel4_segitiga.setLayout(jPanel4_segitigaLayout);
        jPanel4_segitigaLayout.setHorizontalGroup(
                jPanel4_segitigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4_segitigaLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jButton4_segitiga)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4_segitigaLayout.setVerticalGroup(
                jPanel4_segitigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4_segitigaLayout.createSequentialGroup()
                                .addContainerGap(87, Short.MAX_VALUE)
                                .addComponent(jButton4_segitiga, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114))
        );

        Bangun2D.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Bangun2D.setForeground(new java.awt.Color(255, 255, 255));
        Bangun2D.setText("Bangun 2 Dimensi");

        LuasdanKeliling.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LuasdanKeliling.setForeground(new java.awt.Color(255, 255, 255));
        LuasdanKeliling.setText("Luas dan Keliling");

        inputPanjang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inputPanjang.setForeground(new java.awt.Color(239, 192, 80));
        inputPanjang.setText("Inputkan Panjang");

        inputLebar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inputLebar.setForeground(new java.awt.Color(239, 192, 80));
        inputLebar.setText("Inputkan Lebar");

        inputSisiJari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inputSisiJari.setForeground(new java.awt.Color(239, 192, 80));
        inputSisiJari.setText("Inputkan Sisi/Jari-jari");

        jTextField1_panjang.setText("panjang");
        jTextField1_panjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_panjangActionPerformed(evt);
            }
        });

        jTextField2_lebar.setText("lebar");
        jTextField2_lebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_lebarActionPerformed(evt);
            }
        });

        jTextField3_sisijari.setText("sisi/jari-jari");

        jButton5_exit.setBackground(new java.awt.Color(255, 255, 204));
        jButton5_exit.setText("EXIT");
        jButton5_exit.setBorderPainted(false);
        jButton5_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_exitActionPerformed(evt);
            }
        });

        jButton6_hitung.setBackground(new java.awt.Color(249, 152, 70));
        jButton6_hitung.setText("HITUNG");
        jButton6_hitung.setBorderPainted(false);
        jButton6_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6_hitungActionPerformed(evt);
            }
        });

        jButton7_reset.setBackground(new java.awt.Color(249, 152, 70));
        jButton7_reset.setText("RESET");
        jButton7_reset.setBorderPainted(false);
        jButton7_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7_resetActionPerformed(evt);
            }
        });

        LuasArea.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LuasArea.setForeground(new java.awt.Color(239, 192, 80));
        LuasArea.setText("Luas Area");

        Keliling.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Keliling.setForeground(new java.awt.Color(239, 192, 80));
        Keliling.setText("Keliling");

        hasilLuas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        hasilKeliling.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel2_persegi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1_segiempat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel3_lingkaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel4_segitiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(52, 52, 52)
                                                                .addComponent(LuasdanKeliling))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(91, 91, 91)
                                                                .addComponent(Bangun2D))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(26, 26, 26)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(inputPanjang)
                                                                                        .addComponent(jTextField1_panjang))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(inputLebar, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(jTextField2_lebar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                .addGap(28, 28, 28)
                                                                                                .addComponent(jTextField3_sisijari, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                .addGap(23, 23, 23)
                                                                                                .addComponent(inputSisiJari))))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGap(6, 6, 6)
                                                                                .addComponent(LuasArea)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(Keliling))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(jButton5_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                                .addGap(61, 61, 61))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addComponent(jButton6_hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton7_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(hasilLuas)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(hasilKeliling)
                                                .addGap(89, 89, 89))))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(LuasdanKeliling)
                                                .addGap(18, 18, 18)
                                                .addComponent(Bangun2D)
                                                .addGap(18, 18, 18)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(inputPanjang)
                                                        .addComponent(inputLebar)
                                                        .addComponent(inputSisiJari))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextField1_panjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField2_lebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField3_sisijari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                .addGap(6, 6, 6))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel3_lingkaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel2_persegi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jPanel1_segiempat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel4_segitiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addContainerGap())
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton6_hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton7_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(LuasArea)
                                                        .addComponent(Keliling))
                                                .addGap(25, 25, 25)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(hasilLuas)
                                                        .addComponent(hasilKeliling))
                                                .addGap(18, 18, 18)
                                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton5_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7_resetActionPerformed
        // TODO add your handling code here:
        jTextField1_panjang.setText("");
        jTextField2_lebar.setText("");
        jTextField3_sisijari.setText("");

        persegi = false;
        segiempat = false;
        segitiga = false;
        lingkaran = false;

    }//GEN-LAST:event_jButton7_resetActionPerformed

    private void jButton6_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6_hitungActionPerformed
        // TODO add your handling code here:
        double p;
        double l;
        double luas = 0;
        double keliling = 0;

        // membuat object
        if (persegi == true){
            p = Double.parseDouble(jTextField3_sisijari.getText());
            l = Double.parseDouble(jTextField3_sisijari.getText());
            SegiEmpat bentuk = new SegiEmpat(p, l);
            luas = bentuk.luas();
            keliling = bentuk.keliling();
        }
        else if (lingkaran == true){
            p = Double.parseDouble(jTextField3_sisijari.getText());
            l = Double.parseDouble(jTextField3_sisijari.getText());
            Lingkaran bentuk = new Lingkaran(p, l);
            luas = bentuk.luas();
            keliling = bentuk.keliling();
        }
        else if (segitiga == true){
            p = Double.parseDouble(jTextField1_panjang.getText());
            l = Double.parseDouble(jTextField2_lebar.getText());
            Segitiga bentuk = new Segitiga(p, l);
            luas = bentuk.luas();
            keliling = bentuk.keliling();
        }
        else if (segiempat == true){
            p = Double.parseDouble(jTextField1_panjang.getText());
            l = Double.parseDouble(jTextField2_lebar.getText());
            SegiEmpat bentuk = new SegiEmpat(p, l);
            luas = bentuk.luas();
            keliling = bentuk.keliling();
        }

        // menampilkan luas
        String luasstr = String.format("%.2f", luas);
        hasilLuas.setText(luasstr);

        //menampilkan keliling
        String kelilingstr = String.format("%.2f", keliling);
        hasilKeliling.setText(kelilingstr);

//        }

    }//GEN-LAST:event_jButton6_hitungActionPerformed

    private void jButton5_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5_exitActionPerformed

    private void jTextField2_lebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_lebarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_lebarActionPerformed

    private void jTextField1_panjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_panjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_panjangActionPerformed

    private void jButton2_persegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_persegiActionPerformed
        // TODO add your handling code here:
        ShapeApp.persegi = true;
        JOptionPane.showMessageDialog(this, "Masukkan nilai sisi di kolom input!");
    }//GEN-LAST:event_jButton2_persegiActionPerformed

    private void jButton3_lingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_lingkaranActionPerformed
        // TODO add your handling code here:
        ShapeApp.lingkaran = true;
        JOptionPane.showMessageDialog(this, "Masukkan nilai jari-jari di kolom input!");
    }//GEN-LAST:event_jButton3_lingkaranActionPerformed

    private void jButton1_segiempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_segiempatActionPerformed
        // TODO add your handling code here:
        ShapeApp.segiempat = true;
        JOptionPane.showMessageDialog(this, "Masukkan nilai panjang dan lebar di kolom input!");
    }//GEN-LAST:event_jButton1_segiempatActionPerformed

    private void jButton4_segitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_segitigaActionPerformed
        // TODO add your handling code here:
        ShapeApp.segitiga = true;
        JOptionPane.showMessageDialog(this, "Masukkan nilai panjang dan lebar di kolom input!");
    }//GEN-LAST:event_jButton4_segitigaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShapeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShapeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShapeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShapeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShapeApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bangun2D;
    private javax.swing.JLabel Keliling;
    private javax.swing.JLabel LuasArea;
    private javax.swing.JLabel LuasdanKeliling;
    private javax.swing.JLabel hasilKeliling;
    private javax.swing.JLabel hasilLuas;
    private javax.swing.JLabel inputLebar;
    private javax.swing.JLabel inputPanjang;
    private javax.swing.JLabel inputSisiJari;
    private javax.swing.JButton jButton1_segiempat;
    private javax.swing.JButton jButton2_persegi;
    private javax.swing.JButton jButton3_lingkaran;
    private javax.swing.JButton jButton4_segitiga;
    private javax.swing.JButton jButton5_exit;
    private javax.swing.JButton jButton6_hitung;
    private javax.swing.JButton jButton7_reset;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel1_segiempat;
    private javax.swing.JPanel jPanel2_persegi;
    private javax.swing.JPanel jPanel3_lingkaran;
    private javax.swing.JPanel jPanel4_segitiga;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1_panjang;
    private javax.swing.JTextField jTextField2_lebar;
    private javax.swing.JTextField jTextField3_sisijari;
}
// End of variables declaration//GEN-END:variables

